# Generated by Django 5.2.5 on 2025-10-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
