# Generated by Django 5.2.5 on 2025-11-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemphoto_image_alter_itemphoto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
