# Generated by Django 5.2.5 on 2025-11-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_a_id', models.UUIDField()),
                ('user_b_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField()),
                ('sender_id', models.UUIDField()),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
    ]
